# Generated by Django 6.0 on 2025-12-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category_id',
            new_name='category',
        ),
    ]
